spring:
  datasource:
    url: jdbc:h2:mem:testdb

  config:
    activate:
      on-profile: ci

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect